### ISSUE TITLE
'go list' approach doesn't work for some projects

### ISSUE THREAD

**Issue by sknaumov** [tianon/debian-dh-golang#1]
I have problems with dh_golang after [this commit](https://github.com/tianon/debian-dh-golang/commit/7c3fbec6ea92294477fa8910264fe9bd823f21c3), as it started to use 'go list' utility, which can't find anything in my project, as in its root there is only Makefile and no .go files.

Is there any workaround to make 'go list' to search into subdirectories?

**Comment by tianon** [comment]
Whoops, looks like I need to disable issues on this repo -- this is a personal mirror of the Debian repo, and hasn't even been touched in quite some time.  You'll want to go to https://tracker.debian.org/pkg/dh-golang and/or https://bugs.debian.org/src:dh-golang to file a bug on the `dh-golang` package properly.
